# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1582283069e19382b7ec86056cc5c4cb1dda43a75fac4f09c6462e9ab500af785c9828d85529d26e66a04625a19246f60f77ed143a6ae610953d12ead4658721

test:
  secret_key_base: ef130d5fde25691e55d05b5affd76200e71aaa38cd854204cce63a8c08904651aae6a9f78e78421c5e2d8a06f7ad54854824afee5703c8d5a0d16ab4ba30037a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
